insert into raf_state_domn (state_id, state_abbr, state_nm, capital) values
('101', 'AL', 'Alabama', 'Montgomery'),
('102', 'AK', 'Alaska', 'Juneau'),
('103', 'AZ', 'Arizona', 'Phoenix'),
('104', 'AR', 'Arkansas', 'Little Rock'),
('105', 'CA', 'California', 'Sacramento'),
('106', 'CO', 'Colorado', 'Denver'),
('107', 'CT', 'Connecticut', 'Hartford'),
('108', 'DE', 'Delaware', 'Dover'),
('109', 'FL', 'Florida', 'Tallahassee'),
('110', 'GA', 'Georgia', 'Atlanta'),
('111', 'HI', 'Hawaii', 'Honolulu'),
('112', 'ID', 'Idaho', 'Boise'),
('113', 'IL', 'Illinois', 'Springfield'),
('114', 'IN', 'Indiana', 'Indianapolis'),
('115', 'IA', 'Iowa', 'Des Moines'),
('116', 'KS', 'Kansas', 'Topeka'),
('117', 'KY', 'Kentucky', 'Frankfort'),
('118', 'LA', 'Louisiana', 'Baton Rouge'),
('119', 'ME', 'Maine', 'Augusta'),
('120', 'MD', 'Maryland', 'Annapolis'),
('121', 'MA', 'Massachusetts', 'Boston'),
('122', 'MI', 'Michigan', 'Lansing'),
('123', 'MN', 'Minnesota', 'Saint Paul'),
('124', 'MS', 'Mississippi', 'Jackson'),
('125', 'MO', 'Missouri', 'Jefferson City'),
('126', 'MT', 'Montana', 'Helena'),
('127', 'NE', 'Nebraska', 'Lincoln'),
('128', 'NV', 'Nevada', 'Carson City'),
('129', 'NH', 'New Hampshire', 'Concord'),
('130', 'NJ', 'New Jersey', 'Trenton'),
('131', 'NM', 'New Mexico', 'Santa Fe'),
('132', 'NY', 'New York', 'Albany'),
('133', 'NC', 'North Carolina', 'Raleigh'),
('134', 'ND', 'North Dakota', 'Bismarck'),
('135', 'OH', 'Ohio', 'Columbus'),
('136', 'OK', 'Oklahoma', 'Oklahoma City'),
('137', 'OR', 'Oregon', 'Salem'),
('138', 'PA', 'Pennsylvania', 'Harrisburg'),
('139', 'RI', 'Rhode Island', 'Providence'),
('140', 'SC', 'South Carolina', 'Columbia'),
('141', 'SD', 'South Dakota', 'Pierre'),
('142', 'TN', 'Tennessee', 'Nashville'),
('143', 'TX', 'Texas', 'Austin'),
('144', 'UT', 'Utah', 'Salt Lake City'),
('145', 'VT', 'Vermont', 'Montpelier'),
('146', 'VA', 'Virginia', 'Richmond'),
('147', 'WA', 'Washington', 'Olympia'),
('148', 'WV', 'West Virginia', 'Charleston'),
('149', 'WI', 'Wisconsin', 'Madison'),
('150', 'WY', 'Wyoming', 'Cheyenne'),
('151', 'DC', 'District of Columbia', 'Washington'),
('152', 'AS', 'American Samoa', 'Pago Pago'),
('153', 'GU', 'Guam', 'Hagåtña'),
('154', 'MP', 'Northern Mariana Islands', 'Saipan'),
('155', 'PR', 'Puerto Rico', 'San Juan'),
('156', 'VI', 'U.S. Virgin Islands', 'Charlotte Amalie');
