create table raf_person (
    person_id varchar(12) primary key,
    first_nm varchar(50) not null,
    mid_nm varchar(50),
    last_nm varchar(50) not null,
    full_nm varchar(100),
    birth_dt date,
    dth_dt date,
    website varchar(100),
    office_loc_ln1 varchar(100),
    office_loc_ln2 varchar(100),
    phone varchar(16),
    state varchar(40),
    state_abbr varchar(3),
    current_district int,
    current_mem varchar(6),
    bio text,
    email varchar(100),
    img_url varchar(100),
    img_attribution varchar(250),
    party_mem char(1),
    party varchar(25),
    party_st_yr int,
    create_ts timestamp,
    update_ts timestamp
);
