CREATE TABLE RAF_LEADERSHIP (
    LEADERSHIP_ID SERIAL PRIMARY KEY,
    PERSON_ID VARCHAR(12) REFERENCES RAF_PERSON(PERSON_ID),
    CONGRESS VARCHAR(3),
    LEADERSHIP_TYPE VARCHAR(100),
    CURRENT_LEADER VARCHAR(6),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
)