CREATE TABLE RAF_SPONS_LEGISLATION (
    SPON_LEG_ID VARCHAR(12) PRIMARY KEY,
    PERSON_ID VARCHAR(12) REFERENCES RAF_PERSON(PERSON_ID),
    BILL_ID VARCHAR(15) REFERENCES RAF_BILL(BILL_ID),
    SPONSOR_TYPE VARCHAR(20) NOT NULL,
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);