CREATE TABLE RAF_TERM (
    TERM_ID SERIAL PRIMARY KEY,
    PERSON_ID VARCHAR(12) REFERENCES RAF_PERSON(PERSON_ID),
    CHAMBER VARCHAR(100),
    CONGRESS INTEGER,
    DISTRICT INTEGER,
    END_YEAR INTEGER,
    MEMBER_TYPE VARCHAR(100),
    START_YEAR INTEGER,
    STATE_CODE VARCHAR(10),
    STATE_NAME VARCHAR(100),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);