CREATE TABLE RAF_BILL_RELATED_BILLS (
    BILL_ID VARCHAR(50),
    RELATED_BILL_ID VARCHAR(50),
    PRIMARY KEY (BILL_ID, RELATED_BILL_ID),
    FOREIGN KEY (BILL_ID) REFERENCES RAF_BILL(BILL_ID) ON DELETE CASCADE,
    FOREIGN KEY (RELATED_BILL_ID) REFERENCES RAF_BILL(BILL_ID) ON DELETE CASCADE
);