create table raf_bill (
    bill_id varchar(15) primary key,
    bill_no varchar(6),
    bill_title text,
    introduced_dt date,
    latest_action_dt date,
    latest_action_txt text,
    policy_area varchar(255),
    congress varchar(3),
    bill_type varchar(10),
    origin_chamber varchar(40),
    origin_chamber_cd varchar(4),
    summary_action_dt date,
    summary_action_desc varchar(255),
    summary_txt text,
    sponsors_txt text,
    law_no varchar(12),
    law_type varchar(25),
    is_law_fl varchar(1),
    legislative_subjects text,
    create_ts timestamp,
    update_ts timestamp
);