CREATE TABLE RAF_COMMITTEE (
    COMMITTEE_ID VARCHAR(20) PRIMARY KEY,
    CHAMBER VARCHAR(50),
    COMM_TYPE_CD VARCHAR(50),
    COMM_NAME VARCHAR(255),
    SYS_CODE VARCHAR(50),
    URL_SRC VARCHAR(255),
    PARENT_ID VARCHAR(12),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    FOREIGN KEY (PARENT_ID) REFERENCES RAF_COMMITTEE(COMMITTEE_ID)
);