CREATE TABLE RAF_PERSON_CONGRESS (
    PERSON_ID VARCHAR(12) NOT NULL,
    CONGRESS_ID INT NOT NULL,
    PRIMARY KEY (PERSON_ID, CONGRESS_ID),
    FOREIGN KEY (PERSON_ID) REFERENCES RAF_PERSON(PERSON_ID),
    FOREIGN KEY (CONGRESS_ID) REFERENCES RAF_CONGRESS(CONGRESS_ID)
);