ALTER TABLE RAF_BILL ADD FULLTEXT INDEX idx_raf_bill_fulltext (
    BILL_TITLE,
    SUMMARY_TXT,
    BILL_NO,
    BILL_TYPE,
    ORIGIN_CHAMBER,
    POLICY_AREA,
    LEGISLATIVE_SUBJECTS,
    SPONSORS_TXT
);
