CREATE TABLE RAF_BILL (
    BILL_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BILL_NO VARCHAR(10) NOT NULL,
    BILL_TITLE VARCHAR(255) NOT NULL,
    CONGRESS INT NOT NULL,
    SUMMARY TEXT,
    BILL_TYPE VARCHAR(50) NOT NULL,
    CURRENT_STATUS VARCHAR(100),
    SUBJECT_AREA VARCHAR(255),
    CHAMBER VARCHAR(50) NOT NULL,
    SPONSOR_ID BIGINT,
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    CONSTRAINT FK_SPONSOR FOREIGN KEY (SPONSOR_ID) REFERENCES RAF_PERSON(PERSON_ID)
);