CREATE TABLE RAF_BILL_TEXT (
    TEXT_ID VARCHAR(12) NOT NULL PRIMARY KEY,
    BILL_ID VARCHAR(12) NOT NULL,
    VERSION_DATE DATE,
    VERSION_TYPE VARCHAR(255),
    FORMATTED_TEXT_URL TEXT,
    PDF_URL TEXT,
    XML_URL TEXT,
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    CONSTRAINT FK_BILL_TEXT_BILL_ID FOREIGN KEY (BILL_ID) REFERENCES RAF_BILL (BILL_ID)
);