CREATE TABLE RAF_BILL (
    BILL_ID VARCHAR(12) PRIMARY KEY,
    BILL_NO VARCHAR(10),
    BILL_TITLE VARCHAR(1000),
    INTRODUCED_DT DATE,
    LATEST_ACTION_DT DATE,
    LATEST_ACTION_TXT TEXT,
    POLICY_AREA VARCHAR(255),
    CONGRESS INT,
    BILL_TYPE VARCHAR(50),
    ORIGIN_CHAMBER VARCHAR(40),
    ORIGIN_CHAMBER_CD VARCHAR(4),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);