CREATE TABLE RAF_PERSON (
    PERSON_ID VARCHAR(12) PRIMARY KEY,
    FIRST_NM VARCHAR(50) NOT NULL,
    MID_NM VARCHAR(50),
    LAST_NM VARCHAR(50) NOT NULL,
    BIRTH_DT DATE,
    DTH_DT DATE,
    WEBSITE VARCHAR(100),
    OFFICE_LOC VARCHAR(100),
    PHONE VARCHAR(11),
    STATE VARCHAR(2),
    DISTRICT INT,
    BIO TEXT,
    EMAIL VARCHAR(100),
    PHOTO_URL VARCHAR(100),
    PARTY_MEM CHAR(1),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);
