CREATE TABLE RAF_CONGRESS (
    CONGRESS_ID INT PRIMARY KEY,
    CONGRESS_NAME VARCHAR(255),
    CONGRESS_NUMBER INT NOT NULL,
    START_YEAR VARCHAR(255),
    END_YEAR VARCHAR(255),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);