CREATE TABLE RAF_BILL_ACTION (
    ACTION_ID VARCHAR(12) PRIMARY KEY,
    BILL_ID VARCHAR(12),
    ACTION_CD VARCHAR(10),
    ACTION_DT DATE,
    SRC_SYS_CD INT,
    SRC_NM VARCHAR(50),
    ACTION_TXT VARCHAR(250),
    ACTION_TYPE VARCHAR(40),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    CONSTRAINT FK_BILL_ACTION_BILL_ID FOREIGN KEY (BILL_ID) REFERENCES RAF_BILL (BILL_ID)
);