CREATE TABLE RAF_SPONS_LEGISLATION (
    SPON_LEG_ID VARCHAR(12) PRIMARY KEY,
    PERSON_ID VARCHAR(12) NOT NULL,
    BILL_ID VARCHAR(24) NOT NULL,
    SPONSOR_TYPE VARCHAR(20) NOT NULL,
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    CONSTRAINT FK_SPONS_LEG_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES RAF_PERSON (PERSON_ID),
    CONSTRAINT FK_SPONS_LEG_BILL_ID FOREIGN KEY (BILL_ID) REFERENCES RAF_BILL (BILL_ID)
);