CREATE TABLE RAF_SESSION (
    SESSION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    CHAMBER VARCHAR(255) NOT NULL,
    NUMBER INT NOT NULL,
    TYPE VARCHAR(255),
    START_DATE DATE,
    END_DATE DATE,
    CONGRESS_ID INT NOT NULL,
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    FOREIGN KEY (CONGRESS_ID) REFERENCES RAF_CONGRESS(CONGRESS_ID)
);