CREATE TABLE RAF_MEM_SPONS_LEGISLATION (
    SPON_LEG_ID VARCHAR(12),
    PERSON_ID VARCHAR(12),
    CONGRESS INT,
    INTRO_DT DATE,
    LATEST_ACTION_DT DATE,
    LATEST_ACTION_TXT VARCHAR(250),
    BILL_NO INT,
    BILL_TYPE VARCHAR(12),
    POLICY_AREA VARCHAR(50),
    LEG_TITLE VARCHAR(1000),
    LEG_TEXT VARCHAR(250),
    URL_SRC VARCHAR(250),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP,
    CONSTRAINT FK_SPONS_LEG_PERSON_ID FOREIGN KEY (PERSON_ID) REFERENCES RAF_PERSON (PERSON_ID)
);