CREATE TABLE RAF_BILL_ACTION (
    ACTION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    BILL_ID VARCHAR(15) REFERENCES RAF_BILL(BILL_ID),
    ACTION_CD VARCHAR(10),
    ACTION_DT DATE,
    SRC_SYS_CD INT,
    SRC_NM VARCHAR(50),
    ACTION_TXT VARCHAR(1000),
    ACTION_TYPE VARCHAR(40),
    COMMITTEE_REF VARCHAR(2000),
    CREATE_TS TIMESTAMP,
    UPDATE_TS TIMESTAMP
);