CREATE TABLE RAF_BILL_COMMITTEE (
    BILL_ID VARCHAR(12) NOT NULL,
    COMMITTEE_ID VARCHAR(12) NOT NULL,
    PRIMARY KEY (BILL_ID, COMMITTEE_ID),
    FOREIGN KEY (BILL_ID) REFERENCES RAF_BILL (BILL_ID),
    FOREIGN KEY (COMMITTEE_ID) REFERENCES RAF_COMMITTEE (COMMITTEE_ID)
);
